### PR TITLE
chore: separate the dev dependencies

### PR DESCRIPTION
**Pull request by tvuillemin**
Hi.

The idea here is to keep the dev' dependencies separated from the production ones.

At the moment, when using your package, the final production images embed both yapf and unify, although they are useless at runtime. The goal of this PR is to solve this inconvenience.

Cheers.

### CODE REVIEW

**Comment by clayrisser** [comment]
Thanks @tvuillemin

**Comment by tvuillemin** [comment]
You're welcome, thanks for reviewing.

Could you please release a 0.1.2 when you have a moment ?

**Comment by clayrisser** [comment]
Sure thing. I'll do that now.

**Comment by clayrisser** [comment]
I just released a new version.

https://pypi.org/project/markdown-strikethrough/0.1.2/

**Pull request merged**
